// Netlify build script — generates public/config.js from env vars
// Run automatically by Netlify before deploy
// Local dev: node build.js (reads from .env or uses placeholders)

const fs   = require('fs');
const path = require('path');

const token  = process.env.GITHUB_TOKEN  || 'YOUR_GITHUB_TOKEN';
const gistId = process.env.GIST_ID       || '6460a6dfda90fbea4aae70f0ef973bfb';
const file   = process.env.GIST_FILE     || 'uptracker_data.json';

const content = `/* Auto-generated by build.js — DO NOT edit manually */
window.UPTRACKER_CONFIG = {
  GITHUB_TOKEN: '${token}',
  GIST_ID:      '${gistId}',
  GIST_FILE:    '${file}',
};
`;

const outPath = path.join(__dirname, 'public', 'config.js');
fs.writeFileSync(outPath, content);
console.log(`✅ config.js generated (token: ${token.slice(0,8)}...)`);
