// Netlify build script — generates public/config.js before deploy
const fs   = require('fs');
const path = require('path');

// Token comes from Netlify env var (set in dashboard)
// Fallback only used if env var is missing
const token  = process.env.GITHUB_TOKEN  || '';
const gistId = process.env.GIST_ID       || '6460a6dfda90fbea4aae70f0ef973bfb';
const file   = process.env.GIST_FILE     || 'uptracker_data.json';

if (!token) {
  console.error('❌ GITHUB_TOKEN env var is missing! Set it in Netlify dashboard.');
  process.exit(1);
}

const content = `/* Auto-generated by build.js */\nwindow.UPTRACKER_CONFIG = {\n  GITHUB_TOKEN: '${token}',\n  GIST_ID:      '${gistId}',\n  GIST_FILE:    '${file}',\n};\n`;

const outPath = path.join(__dirname, 'public', 'config.js');
fs.writeFileSync(outPath, content);
console.log(`✅ config.js generated — token: ${token.slice(0,12)}...`);
