// Netlify build script — generates public/config.js before deploy
const fs   = require('fs');
const path = require('path');
const crypto = require('crypto');

const token      = process.env.GITHUB_TOKEN  || '';
const gistId     = process.env.GIST_ID       || '6460a6dfda90fbea4aae70f0ef973bfb';
const file       = process.env.GIST_FILE     || 'uptracker_data.json';

// ENCRYPT_KEY: used to encrypt CF tokens before storing in Gist
// Generate a random one if not set (won't be able to decrypt existing tokens)
let encryptKey = process.env.ENCRYPT_KEY || '';
if (!encryptKey) {
  encryptKey = crypto.randomBytes(32).toString('hex');
  console.warn('⚠️  ENCRYPT_KEY not set — generated random key. Set ENCRYPT_KEY in Netlify env vars for persistence.');
}

if (!token) {
  console.error('❌ GITHUB_TOKEN env var is missing! Set it in Netlify dashboard.');
  process.exit(1);
}

const content = `/* Auto-generated by build.js */
window.UPTRACKER_CONFIG = {
  GITHUB_TOKEN:  '${token}',
  GIST_ID:       '${gistId}',
  GIST_FILE:     '${file}',
  ENCRYPT_KEY:   '${encryptKey}',
};
`;

const outPath = path.join(__dirname, 'public', 'config.js');
fs.writeFileSync(outPath, content);
console.log(`✅ config.js generated — token: ${token.slice(0,12)}... encryptKey: ${encryptKey.slice(0,8)}...`);
